export { default as Switch } from './Switch/Switch.vue';
export { default as Button } from './Button/Button.vue';
export { default as Tabs } from './Tabs/Tabs.vue';
export { default as Tab } from './Tabs/Tab.vue';
export { default as Dialog } from './Dialog/Dialog.vue';
export { default as Input } from './Input/Input.vue';
export { default as ButtonGroup} from './Button/ButtonGroup.vue';
export { default as Row} from './Grid/Row.vue';
export { default as Col} from './Grid/Col.vue';
export { default as Layout} from './Layout/Layout.vue';
export { default as Header} from './Layout/Header.vue';
export { default as Content} from './Layout/Content.vue';
export { default as Footer} from './Layout/Footer.vue';
export { default as Sider} from './Layout/Sider.vue';
export { default as Toast} from './Toast/Toast.vue';
export { default as Popover} from './Popover/Popover.vue';
export { default as Collapse} from './Collapse/Collapse.vue';
export { default as CollapseItem} from './Collapse/CollapseItem.vue';
export { default as Selector} from './Selector/Selector.vue';
export { default as Index} from './Selector/Index.vue';
export { default as Checkbox} from './Checkbox/Checkbox.vue';
export { default as Magnifier} from './Magnifier/Magnifier.vue';
export { default as Rate} from './Rate/Rate.vue';
export { openDialog as openDialog } from './Dialog/openDialog';
