export { default as Switch } from './Switch.vue';
export { default as Button } from './Button.vue';
export { default as Tabs } from './Tabs.vue';
export { default as Tab } from './Tab.vue';
export { default as Dialog } from './Dialog.vue';
export { default as Input } from './Input.vue';
export { default as ButtonGroup} from './ButtonGroup.vue';
export { default as Row} from './Row.vue';
export { default as Col} from './Col.vue';
export { openDialog as openDialog } from './openDialog';